import math
from turtle import *
edge_length = 144
def teleport(distance):
    penup()      
    forward(distance)
    pendown()
teleport(edge_length)
color('red')
begin_fill()
left(90)
forward(edge_length/2)
left(45)
forward(edge_length/(2*math.sqrt(2)))
left(45)
forward(edge_length/2)
left(45)
forward(edge_length/(2*math.sqrt(2)))
right(90)
forward(edge_length/(2*math.sqrt(2)))
left(45)
forward(edge_length/2)
left(45)
forward(edge_length/(2*math.sqrt(2)))
left(45)
forward(edge_length/2)
left(45)
forward(edge_length*math.sqrt(2))
left(90)
forward(edge_length*math.sqrt(2))
end_fill()
teleport(edge_length)
